Bump dependencies, fix invalid access to fields, gh workflow
HeartPattern/Exhibitionism pull request #4
Opened 2022-10-23 13:35 UTC by Bixilon

As the commits say

2022-10-25 13:50 UTC, HeartPattern requested changes

2022-10-25 13:50 UTC, HeartPattern commented on src/main/kotlin/kr/heartpattern/exhibitionism/ExhibitionismTransformer.kt
> +            if (type != Type.FIELD || option.noStaticFinal || !staticFinal) {
```suggestion
            if (type != Type.FIELD || !option.noStaticFinal || !staticFinal) {
```
option.noStaticFinal should be false?

2022-10-25 13:50 UTC, HeartPattern commented on src/main/kotlin/kr/heartpattern/exhibitionism/App.kt
readme.md should be updated too!

2022-10-25 15:41 UTC, Bixilon commented
Absolutely right, fixed!

2022-10-25 16:30 UTC, Bixilon commented
No wait, it should be the opposite. If we static final should be removed (`noStaticFinal`), we remove it. Otherwise we only remove it if it is not static final. right?

2022-10-29 06:36 UTC, HeartPattern commented
Oh, naming is really confusing.. As README.md said, `noStaticFinal` option is "do not modify static final" field. Maybe we should rename it to `ignoreStaticFinal` or something.

2022-10-29 06:42 UTC, merged